In [0]:
try:
  answer=5/0
  print(int(answer))
except:
  print("An execption occured, check the denominotor")
else:
  print("It will never execute")
finally:
  print("This is an example of try except concept.")


An execption occured, check the denominotor
This is an example of try except concept.


In [0]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
"""words=[]
try:
  for i in range(0,2):
    for j in range(0,2):
      for k in range(0,2):
        words=subjects[i]+" "+verbs[j]+" "+objects[k]+"."
        print(words)
except Exception as e:
  print(e)"""

words1=[words for i in range(0,2) for j in range(0,2) for k in range(0,2) subjects[i]+" "+verbs[j]+" "+objects[k]+"." ]
print(words1)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


**Task 2:**

**1.**

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [21]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = int(input("Enter the dimension of the matrix"))
def checkIncreasingFlag(flag):
  if flag=="false":
    print(np.vander(x, N))
  else:
    print(np.vander(x, N,increasing=True))
checkIncreasingFlag("false")

Enter the dimension of the matrix3
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
